# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Voodoo
version:      1.13
version_from: lib/Apache/Voodoo/Handler.pm
installdirs:  site
requires:
    Apache::DBI:                   0.94
    Apache::Request:               1.33
    Apache::Session:               1.6
    Config::General:               2.27
    Email::Valid:                  0.15
    HTML::Template:                2.7
    IPC::Shareable:                0.6
    IPC::SharedCache:              1.3
    Time::HiRes:                   1.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
