# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Voodoo
version:      2.0400
version_from: lib/Apache/Voodoo.pm
installdirs:  site
requires:
    Apache2::Request:              0
    Apache::DBI:                   0.94
    Apache::Session:               1.6
    Config::General:               2.27
    CPAN:                          1.9205
    Digest::MD5:                   2.36
    Email::Valid:                  0.15
    File::Pid:                     0
    HTML::Template:                2.7
    IPC::SharedCache:              1.3
    Time::HiRes:                   1.65
    XML::Checker::Parser:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
