# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Voodoo
version:      3.0002
version_from: lib/Apache/Voodoo.pm
installdirs:  site
requires:
    Apache2::Cookie:               2.08
    Apache2::Request:              2.08
    Apache::Session:               1.6
    Config::General:               2.27
    CPAN:                          1.9205
    Daemon::Generic:               0.51
    DBI:                           1.609
    Devel::StackTrace:             1.2
    Digest::MD5:                   2.36
    Email::Valid:                  0.15
    Exception::Class:              1.26
    Exception::Class::DBI:         1
    File::Pid:                     1.01
    HTML::Template:                2.7
    IO::Handle::Record:            0.13
    IPC::SharedCache:              1.3
    JSON::DWIW:                    0.32
    Log::Log4perl:                 
    Pod::WSDL:                     0.05
    Proc::UID:                     0.05
    SOAP::Lite:                    0.71
    Time::HiRes:                   1.65
    XML::Checker:                  0.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
