# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Voodoo
version:      1.12
version_from: lib/Apache/Voodoo/Handler.pm
installdirs:  site
requires:
    Apache::DBI:                   0
    Apache::Session:               0
    Config::General:               0
    Email::Valid:                  0
    HTML::Template:                0
    IPC::Shareable:                0
    IPC::SharedCache:              0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
